### ISSUE TITLE
Generated Image Upload Error on nft.storage

### ISSUE THREAD

**Issue by dhairyaostwal** [DineshBS44/RandomizeNFT#1]
Greetings! This is amazing work!

I don't know why it is not saving properly on nft.storage. When I click the CID link which must redirect me to the image it shows an error(screenshot below)
<img width="904" alt="Screenshot 2021-11-29 at 08 28 49" src="https://user-images.githubusercontent.com/50984984/143802022-123607f7-d7e6-4ce4-a4ea-fda5ab90eb8e.png">

Though I checked uploading the image saved locally on nft.storage. Visit the link here - https://bafkreigbalf7fs4schuv3bn7id2ysm4dzsug3stpz22d6jogjczurudxmy.ipfs.dweb.link/

**Comment by DineshBS44** [comment]
Hey @dhairyaostwal!
I have tested the <a href="https://bafkreigbalf7fs4schuv3bn7id2ysm4dzsug3stpz22d6jogjczurudxmy.ipfs.dweb.link/">link</a> that you have sent, but I was able to retrieve the image correctly as shown below.
![image](https://user-images.githubusercontent.com/55662714/143820231-3059eb4b-173e-4829-81c1-15b4b9cba961.png)

I have rarely observed this error before, but not sure why it happens. Anyways, can you check now and see if the same error is being reflected now?

**Comment by dhairyaostwal** [comment]
@DineshBS44 thanks for the reply! I am talking about the following [link](https://bafyreicko4dv77k4f74epytu64jk4tdjy6o73sgbaelnour5wg6sfqd6gm.ipfs.dweb.link/) and [link](https://bafyreiblpuyi6uqvfx3mljocwlao3yvlxa3wxv6d3vn763ogd36lwqjcqa.ipfs.dweb.link/) which were saved in my nft.storage account post running the `server.js` file

The one you're talking about I manually uploaded image.

**Comment by DineshBS44** [comment]
@dhairyaostwal please try adding `/metadata.json` at the end of the links that you have sent. `nft.storage` will not add the file names at the end of the dweb gateway. The client.store method in `server.js` adds a filename to the metadata as `metadata.json`.

Check out the following images where I have successfully retrieved the NFT metadata after appending `/metadata.json` to the links that you have sent.
![image](https://user-images.githubusercontent.com/55662714/143836426-55ebd557-35f1-41b3-a3f3-541e9a9fbbfe.png)
![image](https://user-images.githubusercontent.com/55662714/143836473-361a972f-aa31-49c6-99ee-3b4dbac27151.png)
You can also see that the NFT image link in the metadata has `/randomCharacter.json` appended at the end of the link.

**Comment by dhairyaostwal** [comment]
@DineshBS44 Yes now I understood the working. Rightly explained. One more question - so the image which I retrieve is only saved on to my local storage - inside project directory? 

Overall highly appreciate your work 🎉

**Comment by DineshBS44** [comment]
@dhairyaostwal Thanks!

The Random image is generated using `mixComponents.js` and updated in `randomCharacter.png`. But, when I upload it using `nft.storage`, it stores the image in `Filecoin` and `IPFS` using the filenames that I want it to have. 

After uploading, the image is stored in the decentralized IPFS network which can be retrieved using its `CID`(IPFS Hash). The image is not stored locally, rather the file stored locally is uploaded to `Filecoin` and `IPFS`.

There are many IPFS gateways that can be used with the `CID` hash to retrieve the image. The link that you have sent previously uses `dweb`. But, these gateways have a rate-limiting system and are generally considered slow due to the large number of requests they get. So, for scalability, people use their own IPFS node to retrieve the uploaded files faster. In this case, there will not be any rate limits for a file as the gateway link is their own.

Read <a href="https://medium.com/0xcode/using-ipfs-for-distributed-file-storage-systems-61226e07a6f">this</a> blog to know more about how the p2p network works to store the files.

**Comment by dhairyaostwal** [comment]
Woah! This sounds really interesting @DineshBS44. Would definitely love to work around this 😄 

_Good to close this issue_
